ENV_NAME_DEVELOPMENT_MODE = 'DEVELOPMENT_MODE'
ENV_NAME_FACTORIAL_EMAIL_ADDRESS = 'FACTORIAL_EMAIL_ADDRESS'
ENV_NAME_FACTORIAL_PASSWORD = 'FACTORIAL_PASSWORD'
ENV_NAME_START_HOUR = 'START_HOUR'

ENV_DEFAULT_START_HOUR = 8

CRON_TYPE = 'cron'
CRON_DAY_OF_WEEK = 'mon-fri'

SELENIUM_BINARY_PATH = '/usr/bin/firefox'
SELENIUM_EXECUTABLE_PATH = 'geckodriver/geckodriver'

FACTORIAL_WEBSITE_INIT = 'https://factorialhr.com/users/sign_in'
